language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - PUPPET_GEM_VERSION='~> 2.7'
  - PUPPET_GEM_VERSION='~> 3.0'
before_install:
 - sudo apt-get install -qq libaugeas-dev
notifications:
  email:
    - dev@realmediadigital.com